title: The Deployer
description: >
  Simple Infrastructure As Code solution for Java EE containers (currently only JBoss 7+) pulling from a maven repository.
baseurl: ""
url: "https://t1.github.io/deployer"

# Build settings
theme: minima

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
